name: Deploy to InventoryPresser.com
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  inventorypresser-com-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy to Rocket.net
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: rsync -avz "$GITHUB_WORKSPACE" rzjalis@131.153.207.156:public_html/wp-content/plugins/inventory-presser
          host: 131.153.207.156
          username: rzjalis
          privateKey: ${{ secrets.ROCKET_NET_SSH_KEY_PRIVATE }}
