name: Run phpdoc-parser on InventoryPresser.com
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  inventorypresser-com-run-phpdoc-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Run phpdoc-parser to Build Documentation
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd public_html && wp parser create wp-content/plugins/inventory-presser/ --user=corey
          host: 131.153.207.156
          username: rzjalis
          privateKey: ${{ secrets.ROCKET_NET_SSH_KEY_PRIVATE }}