name: Deploy to InventoryPresser.com
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  inventorypresser-com-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Deploy using rsync to server
      - name: Deploy to Rocket.net
        uses: burnett01/rsync-deployments@7.0.1
        with:
          # -v: verbose
          # -z: compress files during transfer
          # -r: copy files recursively
          # --delete: delete extraneous files from dest dirs
          switches: -vzr --delete
          remote_path: ${{ secrets.ROCKET_NET_PATH }}
          remote_host: ${{ secrets.ROCKET_NET_HOST }}
          remote_user: ${{ secrets.ROCKET_NET_USER }}
          remote_key: ${{ secrets.ROCKET_NET_SSH_KEY_PRIVATE }}
      - name: Install dependencies
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd public_html/wp-content/plugins/inventory-presser && composer install
          host: 131.153.207.156
          username: rzjalis
          privateKey: ${{ secrets.ROCKET_NET_SSH_KEY_PRIVATE }}
      - name: Run phpdoc-parser
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd public_html && wp parser create wp-content/plugins/inventory-presser/ --user=corey
          host: 131.153.207.156
          username: rzjalis
          privateKey: ${{ secrets.ROCKET_NET_SSH_KEY_PRIVATE }}
